config/routes.rb
Mixture::Application.routes.draw do
  constraints subdomain: 'api' do
    root to: 'application#render_not_found'

    namespace :v0, :module => 'api/v0' do

      # Mixes
      resources :mixes, only: [:create, :show, :update] do
        collection do
          get 'popular'
          get 'popular/page/:page', action: :popular

          get 'recent'
          get 'recent/page/:page', action: :recent

          get 'search/:query', action: :search
          get 'search/:query/page/:page', action: :search
        end

        member do
          put 'played', action: :played
          get 'stream', action: :stream
        end
      end

      # Collections
      resources :collections, controller: 'mix_collections', only: [:index, :show] do
        member do
          get 'years'
        end

        collection do
          get 'all'
          get 'page/:page', action: :index
        end

        resources :mixes, only: [:index] do
          get 'page/:page', action: :index, on: :collection
        end
      end

      # Performers
      resources :performers, only: [:index, :show] do
        get 'search', :action => :search, :on => :collection

        resources :mixes, only: [:index] do
          get 'page/:page', action: :index, on: :collection
        end
      end

      # Users
      resources :users, only: [:create]

      resource :u, controller: 'u', only: [:show] do
        resource :favorites, only: [] do
          collection do
            get '', action: :index
            get 'page/:page', action: :index
          end
          member do
            post ':mix_id', action: :create
            delete ':mix_id', action: :destroy
          end
        end
      end
    end

  end

  namespace :admin do
    root to: redirect('/admin/mixes')
    resources :mixes
    resources :mix_collections
    resources :performers
  end

  get 'search/:query', to: 'mixture#index'
  get 'recent', to: 'mixture#index'
  get 'popular', to: 'mixture#index'
  get 'u/favorites', to: 'mixture#index'
  get 'm/:id', to: 'mixes#show'
  get 'collections', to: 'mixture#index'
  get 'ios', to: 'mixture#index'
  get 'c/:collection_id', to: 'mixture#index'
  root to: 'mixture#index'

  match '*all', to: 'application#render_not_found' unless Rails.application.config.consider_all_requests_local
end

app/models/mix_collection.rb
class MixCollection
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Slug

  paginates_per 12

  field :name, type: String
  field :mixes_count, type: Integer, default: 0
  slug :name

  has_many :mixes

  validates_presence_of :name, message: "cannot be blank."
  validates_uniqueness_of :name, message: "is already taken."

  # Do this later.
  attr_accessible :name, as: [ :default, :admin ]

  class << self
    def popular
      order_by([:mixes_count, :desc])
    end

    def paginate(options = {})
      page(options[:page]).per(options[:per_page])
    end
  end

  def years
    self.mixes.only(:debuted_at)
      .order_by(:debuted_at, :desc)
      .collect { |m| m.debuted_at.year }.uniq
  end

  def payload
  	{
      id: id,
  		name: name,
      slug: slug,
  		mix_count: mixes_count
  	}
  end

  def as_json(options={})
  	payload
  end
end

app/controllers/admin/mix_collections_controller.rb
class Admin::MixCollectionsController < Admin::BaseController
	before_filter :find_mix_collection, only: [:edit, :update, :show]

	def index
		@mix_collections = MixCollection.paginate(page: params[:page])
	end

	def show; end

	def edit; end

	def update
		@mix_collection.assign_attributes params[:mix_collection], as: :admin
		if @mix_collection.save
			redirect_to admin_mix_collection_path(@mix_collection), notice: 'Mix Collection updated.'
		else
			render 'edit'
		end
	end

	def new
		@mix_collection = MixCollection.new
	end

	def create
		@mix_collection = MixCollection.new params[:mix_collection], as: :admin
		if @mix_collection.save
			redirect_to admin_mix_collection_path(@mix_collection), notice: 'Mix Collection created.'
		else
			render 'new'
		end
	end

	private
	def find_mix_collection
		@mix_collection = MixCollection.find_by_slug(params[:id]) || not_found
	rescue Mongoid::Errors::DocumentNotFound, BSON::InvalidObjectId
		not_found
	end
end

app/controllers/api/v0/mix_collections_controller.rb
class Api::V0::MixCollectionsController < Api::BaseController
	before_filter :find_mix_collection, only: [:show, :years]

	def all
		render json: MixCollection.order_by(:name, :asc)
	end

	def index
		resp = {
			page: params[:page],
			per_page: params[:per_page],
			total: MixCollection.count,
			models: MixCollection.order_by([:mixes_published_count, :desc]).page(params[:page]).per(params[:per_page])
		}
		render json: resp
	end

	def show
		render json: @mix_collection
	end

	def years
		render json: @mix_collection.years
	end
end

app/views/admin/mix_collections/_form.html.erb
<%= simple_form_for [:admin, @mix_collection], html: { class: 'form-vertical' } do |f| %>
	<% if f.error_notification %>
		<div class="alert alert-error fade in">
			<a class="close" data-dismiss="alert" href="#">&times;</a>
			<%= f.error_notification %>
		</div>
	<% end %>

	<fieldset>
		<legend>Basic Info</legend>
		<%= f.input :name %>
	</fieldset>

	<div class="form-actions">
    <%= f.button :submit, :class => 'btn btn-primary' %>
    <%= submit_tag 'Cancel', :type => :reset, :class => "btn btn-danger" %>
  </div>
<% end %>

app/views/admin/mix_collections/_list_item.html.erb
<a id="<%= dom_id(list_item) %>" class="mix-collection clearfix" href="<%= admin_mix_collection_path list_item %>">
	<div class="pull-left">
		<h5><%= list_item.name %></h5>
	</div>
	<div>
		<p class="audio-processing pull-right">
			<%= list_item.mixes_count %> Mixes
		</p>
	</div>
</a>

app/views/admin/mix_collections/edit.html.erb
<h2>Edit Collection</h2>
<%= render 'form' %>

app/views/admin/mix_collections/index.html.erb
<div class="row-fluid">
	<div class="span12">
			<div class="btn-group pull-right">
				<%= link_to "New Collection", new_admin_mix_collection_path, class: 'btn btn-large' %>
			</div>
	</div>
</div>

<div class="row-fluid">
	<div class="span12">
		<div class="mix-collections">
			<%= render partial: "list_item", collection: @mix_collections %>
		</div>
	</div>
</div>

<div class="row-fluid">
	<div class="span12">
		<%= paginate @mix_collections %>
	</div>
</div>

app/views/admin/mix_collections/new.html.erb
<h2>New Collection</h2>
<%= render 'form' %>

app/views/admin/mix_collections/show.html.erb
<div class="row-fluid">
	<div class="span12">
		<h2>Basic Info</h2>
		<h4>Name</h4>
		<p><%= @mix_collection.name %></p>

		<div class="well">
			<%= link_to "Edit", edit_admin_mix_collection_path(@mix_collection), class: 'btn btn-small' %>
			<%= link_to "Delete", admin_mix_collection_path(@mix_collection), method: :delete, confirm: "Are you sure?", class: 'btn btn-small btn-danger' %>
		</div>

	</div>
</div>