config/routes.rb
Mixture::Application.routes.draw do
  constraints subdomain: 'api' do
    root to: 'application#render_not_found'

    namespace :v0, :module => 'api/v0' do

      # Mixes
      resources :mixes, only: [:create, :show, :update] do
        collection do
          get 'popular'
          get 'popular/page/:page', action: :popular

          get 'recent'
          get 'recent/page/:page', action: :recent

          get 'search/:query', action: :search
          get 'search/:query/page/:page', action: :search
        end

        member do
          put 'played', action: :played
          get 'stream', action: :stream
        end
      end

      # Collections
      resources :collections, controller: 'mix_collections', only: [:index, :show] do
        member do
          get 'years'
        end

        collection do
          get 'all'
          get 'page/:page', action: :index
        end

        resources :mixes, only: [:index] do
          get 'page/:page', action: :index, on: :collection
        end
      end

      # Performers
      resources :performers, only: [:index, :show] do
        get 'search', :action => :search, :on => :collection

        resources :mixes, only: [:index] do
          get 'page/:page', action: :index, on: :collection
        end
      end

      # Users
      resources :users, only: [:create]

      resource :u, controller: 'u', only: [:show] do
        resource :favorites, only: [] do
          collection do
            get '', action: :index
            get 'page/:page', action: :index
          end
          member do
            post ':mix_id', action: :create
            delete ':mix_id', action: :destroy
          end
        end
      end
    end

  end

  namespace :admin do
    root to: redirect('/admin/mixes')
    resources :mixes
    resources :mix_collections
    resources :performers
  end

  get 'search/:query', to: 'mixture#index'
  get 'recent', to: 'mixture#index'
  get 'popular', to: 'mixture#index'
  get 'u/favorites', to: 'mixture#index'
  get 'm/:id', to: 'mixes#show'
  get 'collections', to: 'mixture#index'
  get 'ios', to: 'mixture#index'
  get 'c/:collection_id', to: 'mixture#index'
  root to: 'mixture#index'

  match '*all', to: 'application#render_not_found' unless Rails.application.config.consider_all_requests_local
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>Admin | Mixture.fm</title>

  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1.0">
  <link rel="SHORTCUT ICON" href="<%= image_path 'favicon.png' %>"> 

	<%= stylesheet_link_tag "admin" %>
	<%= csrf_meta_tags %>

</head>

<body>
	<div class="navbar navbar-fixed-top">
	  <div class="navbar-inner">
	    <div class="container-fluid">
	      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </a>
	      <a class="brand" href="#">Mixture.fm</a>
	      <div class="nav-collapse">
	        <ul class="nav">
	          <li class="<%= controller.controller_name == "mixes" ? "active" : "" %>">
	          	<%= link_to "Mixes", admin_mixes_path %>
	          </li>
	          <li class="<%= controller.controller_name == "mix_collections" ? "active" : "" %>">
	          	<%= link_to "Collections", admin_mix_collections_path %>
	          </li>
	          <li class="<%= controller.controller_name == "performers" ? "active" : "" %>">
	          	<%= link_to "Performers", admin_performers_path %>
	          </li>
	        </ul>
	      </div><!--/.nav-collapse -->
	    </div>
	  </div>
	</div>
	
	<% if !flash.empty? %>
	<div id="alert-container">
		<% flash.each do |name, msg| %>
			<%= content_tag(:div, raw(msg), :class => "alert #{name} fade in") %>
		<% end %>
	</div>
	<% end %>

	<div id="admin" class="container-fluid">
		<%= yield :layout %>
	</div>

	<%= javascript_include_tag "admin" %>
	<%= yield :javascript %>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  <%
    set_meta_tags description: "Mixture.fm gives you access to all the best DJ mixes from around the world. Including BBC Radio 1's famous Essential Mix.",
      keywords: "electronic music, dance music, house music, dj, essential mix, bbc radio1, fact mix, fact mag"
  %>
  <%= display_meta_tags site: "Mixture.fm - Mixes for the Masses" %>

  <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1.0">
  <link rel="SHORTCUT ICON" href="<%= image_path 'favicon.png' %>">

  <%= stylesheet_link_tag "mixture" %>
  <%= csrf_meta_tags %>

</head>

<body>
  <div id="mixture">

  </div>
  <div id="fb-root"></div>

  <script type="text/json" id="nav-bootstrap">
    {"collections": <%= MixCollection.popular.limit(5).to_json %> }
  </script>

  <!-- Exceptional! -->
  <script type="text/javascript" src="http://js.exceptional.io/exceptional.js"></script>
  <script type="text/javascript">
    Exceptional.setKey("<%= ENV['EXCEPTIONAL_API_KEY'] %>");
  </script>

  <%= javascript_include_tag "main" %>
  <script type="text/javascript">
    window.fbAsyncInit = function() {
      Mixture.fbInit();
    };

    // Load the SDK Asynchronously
    (function(d){
      var js, id = 'facebook-jssdk'; if (d.getElementById(id)) { return; }
      js = d.createElement('script'); js.id = id; js.async = true;
      js.src = "//connect.facebook.net/en_US/all.js";
      d.getElementsByTagName('head')[0].appendChild(js);
     }(document));
  </script>

  <% if Rails.env.production? %>
    <script type="text/javascript">
      var _gauges = _gauges || [];
      (function() {
        var t   = document.createElement('script');
        t.type  = 'text/javascript';
        t.async = true;
        t.id    = 'gauges-tracker';
        t.setAttribute('data-site-id', '<%= ENV['GAUGES_ID'] %>');
        t.src = '//secure.gaug.es/track.js';
        var s = document.getElementsByTagName('script')[0];
        s.parentNode.insertBefore(t, s);
      })();
    </script>
  <% end %>

</body>
</html>

app/views/layouts/error.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  <%= display_meta_tags site: "Mixture.fm - 404" %>

  <meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1.0">
  <link rel="SHORTCUT ICON" href="<%= image_path 'favicon.png' %>">

  <%= stylesheet_link_tag "mixture" %>

</head>

<body>
  <div id="mixture" class="error-page">
    <%= yield :layout %>
  </div>

  <script type="text/javascript">

    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-31260800-1']);
    _gaq.push(['_trackPageview']);

    (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();

  </script>
</body>
</html>